"""
Stage 1 VLM Smoke Test – Alpamayo Chat Template + Base Qwen3-VL

This script:
1. Uses the exact clip from src/alpamayo_r1/test_inference.py
2. Extracts one image from camera_front_wide_120fov (via extract_test_image.py)
3. Runs inference with the Alpamayo-style chat template (multi-image ready, traj history, CoC start)

NOTE: We are using the base Qwen3-VL-8B-Instruct weights (the same backbone as Alpamayo-R1).
      The generated output will still be nonsensical until the fine-tuned Alpamayo VLM weights are loaded.
The generated CoC and trajectory tokens will be semantically meaningless.
This is a structural validation only.
"""

from pathlib import Path
from mlx_port.vlm_loader import load_vlm, generate_alpamayo_coc, MIN_PIXELS, MAX_PIXELS


# Extracted random front-wide frame (generated by mlx_port/extract_random_front_wide.py)
TEST_IMAGE = Path("reports/stage1_test_image_front_wide.png")


def main():
    if not TEST_IMAGE.exists():
        print(f"Test image not found at {TEST_IMAGE}.")
        print("Please run first on host:")
        print("    python mlx_port/extract_test_image.py")
        return

    model, processor = load_vlm()

    print("\n=== Stage 1 VLM Test (Alpamayo Chat Template) ===")
    print(f"Using image: {TEST_IMAGE}")
    print("Running generate_alpamayo_coc() with base Qwen3-VL weights...")

    # We pass a list with a single image (front-wide) to match the template
    images = [TEST_IMAGE]  # mlx-vlm accepts Path or PIL; list for multi-image support

    output = generate_alpamayo_coc(
        model,
        processor,
        images=images,
        max_tokens=128,
        temperature=0.6,
        min_pixels=MIN_PIXELS,
        max_pixels=MAX_PIXELS,
    )

    print("\n--- Raw VLM Output ---")
    print(output)
    print("\n[Stage 1] Structural test complete (output will be nonsensical until Alpamayo weights are loaded).")


if __name__ == "__main__":
    main()